# Generated by Django 5.2.1 on 2025-06-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
    ]
