image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_FILE: docker-compose.yml

stages:
  - build
  - test
  - deploy

before_script:
  - apk add --no-cache docker-cli docker-compose
  - docker info

build:
  stage: build
  script:
    - echo "🔧 Build des services Docker..."
    - docker-compose build
  only:
    - branches

test:
  stage: test
  script:
    - echo "✅ Tests Django (backend)"
    - docker-compose up -d db
    - sleep 10  # laisse le temps à Postgres de démarrer
    - docker-compose run server poetry run python manage.py migrate
    - docker-compose run server poetry run python manage.py test
    - docker-compose down
  only:
    - branches

deploy:
  stage: deploy
  script:
    - echo "🚀 Déploiement de tous les conteneurs..."
    - docker-compose up -d
  only:
    - main
